### PR TITLE
fix pkg_info while keeping pkgsrc checking.

### PR DESCRIPTION
**Pull request by Izder456**
closed my old pr as my commit history was gross. this is cleaned up.

### CODE REVIEW

**Comment by outpaddling** [comment]
This is also incorrect.  auto-using-pkgsrc implies that the pkg_info in PATH is from pkgsrc.  This should work on *any* operating system, though FreeBSD was excluded, somewhat erroneously.  FreeBSD is the one platform that almost nobody uses pkgsrc on, so I haven't been strict about supporting pkgsrc on FreeBSD until now.  I just committed a correction to auto-package-installed that should make it clearer how to add OpenBSD support.

**Comment by Izder456** [comment]
@outpaddling 

what I believe the issue is is that auto-using-pkgsrc returns true on openbsd, even if it isn't using pkgsrc.

I haven't personally seen many openbsd users using pkgsrc either, it'd probably be better to use openbsd's ports tree like freebsd does currently.

although even then, the ports tree is kept to mainly developer only, and binaries are the only technically supported way to install software outside of base for average non-dev users. this means that many openbsd users won't be using the ports tree.

openbsd's binary package tools clash with pkgsrc too so that could be another reason why many developer users don't use it.

**Comment by outpaddling** [comment]
Then we need to fix auto-using-pkgsrc so it works properly on OpenBSD.

There are occasionally discussions on the pkgsrc lists about pkgsrc on OpenBSD.  Pkgsrc users just have to ensure that their PATH and other env are set up right to avoid conflicts.  This is true on most Linux distros as well.

**Comment by Izder456** [comment]
@outpaddling 

what I believe the issue is is that auto-using-pkgsrc returns true on openbsd, even if it isn't.

I haven't personally seen many openbsd users using pkgsrc either, it'd probably be better to use openbsd's ports tree like freebsd does currently.

openbsd's binary package tools clash with pkgsrc so that could be a primary reason why many users don't use it.

**Pull request closed without merging**
