### PR TITLE
auto-install-packages: add -U option to skip repository update

### LINKED ISSUE #13: auto-install-packages does not allow skipping repository update for FreeBSD pkg install
That would be necessary to fix https://github.com/outpaddling/desktop-installer/issues/45.

### PR DESCRIPTION
**Pull request by Defenso-QTH**
Closes #13

### CODE REVIEW

**Comment by outpaddling** [comment]
This is not a bad idea, but out of curiosity, is this actually a serious problem on your network?  The repo updates add no noticeable delay for me.

**Comment by Defenso-QTH** [comment]
A few seconds each time. And twice because of the additional repo configuration for pkgbase, I think. So it's noticeable when it's called over twenty times.

**Comment by outpaddling** [comment]
Actually, auto-install-packages already passes unrecognized flags like -U on to pkg install, so this would be redundant.  The suggested changes to desktop-installer should work without this.

**Comment by outpaddling** [comment]
You must be far from the package servers.  I assume you've tried various mirrors?

**Pull request closed without merging**
